routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\proyectoController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('proyecto', proyectoController::class);

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/proyecto.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class proyecto extends Model
{
    use HasFactory;

    protected $fillable =[
        'name',
        'Descripcion'
    ];


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/proyectoController.php
<?php

namespace App\Http\Controllers;

use App\Models\proyecto;
use Illuminate\Http\Request;
use Illuminate\View\View;
use Illuminate\Support\Facades\DB;

class proyectoController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $proyectos = DB::table('proyectos')->get();
        return view('proyecto.index', ['proyectos' => $proyectos]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('proyecto.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'name' => 'required|max:255',
            'Descripcion' => 'required',
        ]);

        proyecto::create($request->all());
        return redirect()->route('proyecto.index')->with('succes','Post created successfully.');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function show(proyecto $proyecto)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $proyecto = Proyecto::find($id);
        return view('proyecto.edit', compact('proyecto'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
             'nombre' => 'required|max:255',
             'Descripcion' => 'required',
         ]);
        $proyecto = Proyecto::find($id);
        $proyecto->update($request->all());
        return redirect()->route('proyecto.index')->with('success','Post updates successfully.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\proyecto  $proyecto
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $proyecto = Proyecto::find($id);
        $proyecto -> delete();
        return redirect()-> route('proyecto.index')->with('succes','product deleted successfully');
    }
}

resources/views/proyecto/create.blade.php
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  </head>
  <body>
    <form action="{{ route('proyecto.store') }}" method="post">
      @csrf
      @method('POST')
    <div class="col-5">
      <h1 class="display-6">Registro de proyecto</h1>
      <form action="{{ route('proyecto.store') }}" method="post">
        <div class="mb-3">
      <label for="formGroupExampleInput" class="form-label">Nombre Proyecto</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Agregar proyecto">
      <input type="text" class="form-control" id="Descripcion" name="Descripcion" placeholder="Agregar detalles">
    </br>
      <button class="btn btn-primary" type="submit">Agregar</button>
</div>
     </form>
    </div>
  </div>
</div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/proyecto/edit.blade.php
<form action="{{ route('proyecto.update', $proyecto->id) }}" method="post">
	@csrf
	@method('PUT')
	<div class="form-group">
		<label for="title">Nombre</label>
		<input type ="text" class="form-control" id="name" name="name"
			value="{{ $proyecto->name }}" required>
	</div>
	<div class="form-group">
		<label for="body">Descripcion</label>
		<textarea class="form-control" id="Descripcion" name="Descripcion" rows="3" required>{{ $proyecto->Descripcion }}</textarea>
	</div>
	<button type="submit" class="btn mt-3 btn-primary">Update</button>
</form>

resources/views/proyecto/index.blade.php
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Editar proyecto</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
</head>
    <body>
        <h1>Hello,</h1>

        @foreach ($proyectos as $proyecto)
            <li>{{$proyecto->name}}</li>
            <a href = "{{ route('proyecto.edit', $proyecto->id) }}" class="btn btn-info" style="margin-right: 5px;color: white;"> Editar 
  </a>
   <form action="{{ route('proyecto.destroy', $proyecto->id) }}" method="post" style="display:inline;">
    @csrf
    @method('DELETE')
    <button type="submit" class="btn btn-danger">Borrar</button>
  </form>
        @endforeach
    </body>
</html>